-- Add password reset table for forgot password feature
-- Run this once to add the new table

DROP TABLE IF EXISTS GRN_PASSWORD_RESET;

CREATE TABLE GRN_PASSWORD_RESET (
    RESET_ID INT AUTO_INCREMENT PRIMARY KEY,
    LOGIN_ID VARCHAR(12) NOT NULL,
    TOKEN VARCHAR(255) NOT NULL,
    EXPIRES_AT DATETIME NOT NULL,
    USED TINYINT(1) NOT NULL DEFAULT 0,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_reset_token (TOKEN),
    CONSTRAINT fk_reset_login FOREIGN KEY (LOGIN_ID) 
        REFERENCES GRN_LOGIN(LOGIN_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_reset_token_expires ON GRN_PASSWORD_RESET (TOKEN, EXPIRES_AT, USED);
CREATE INDEX idx_reset_expires ON GRN_PASSWORD_RESET (EXPIRES_AT);

